POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpva3UiLCJpZCI6IjY0NWNkYTViNmMwYmQxNzY1YTg2ZmM4NCIsImlhdCI6MTY4MzgwNzMyOX0.o01QvMpa7qnNqQCvU4EqeW1YSv2IKCqkbMDUhPqbs6M

{
  "_id": "5a422b3a1b54a676234d17f9",
  "title": "Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
  "likes": 12,
  "__v": 0
}